export interface RestrictedImagerySource {
  county: string;
  name: string;
  year: number;
  url: string;
  detail?: string;
  reason: string;
}

export const restrictedImagerySources: readonly RestrictedImagerySource[] = [
  {
    county: "Aitkin",
    name: "Aitkin County 2024 Pictometry",
    year: 2024,
    url: "https://gisweb.co.aitkin.mn.us/arcgis/rest/services/2024PictometryImagery/MapServer",
    detail: "County aerial mosaic",
    reason: "The county exposes a public viewing service, but the Pictometry imagery record does not publish a third-party reuse license for MnMapping.",
  },
  {
    county: "Anoka",
    name: "Anoka County spring 2026 aerials",
    year: 2026,
    url: "https://gis.anokacountymn.gov/anoka_gis/rest/services/Aerials/MapServer",
    detail: "6-inch county imagery",
    reason: "The county service is publicly viewable, but it provides no copyright statement or license granting third-party embedding rights.",
  },
  {
    county: "Anoka",
    name: "Anoka County fall 2025 aerials",
    year: 2025,
    url: "https://gis.anokacountymn.gov/anoka_gis/rest/services/Aerials_Fall/MapServer",
    detail: "6-inch county imagery",
    reason: "The county service is publicly viewable, but it provides no copyright statement or license granting third-party embedding rights.",
  },
  {
    county: "Anoka",
    name: "Anoka County spring 2024 aerials",
    year: 2024,
    url: "https://gis.anokacountymn.gov/anoka_gis/rest/services/Aerials_2024/MapServer",
    detail: "6-inch county imagery",
    reason: "The county service is publicly viewable, but it provides no copyright statement or license granting third-party embedding rights.",
  },
  {
    county: "Anoka",
    name: "Anoka County 2020 aerials",
    year: 2020,
    url: "https://gis.anokacountymn.gov/anoka_gis/rest/services/Aerials_2020/MapServer",
    detail: "Approximately 6-inch county imagery",
    reason: "The county service is publicly viewable, but it provides no copyright statement or license granting third-party embedding rights.",
  },
  {
    county: "Anoka",
    name: "Anoka County 2017 aerials",
    year: 2017,
    url: "https://gis.anokacountymn.gov/anoka_gis/rest/services/Aerials_2017/MapServer",
    detail: "Approximately 6-inch county imagery",
    reason: "The county service is publicly viewable, but it provides no copyright statement or license granting third-party embedding rights.",
  },
  {
    county: "Benton",
    name: "Benton County 2023 EagleView download",
    year: 2023,
    url: "https://www.arcgis.com/home/item.html?id=0fb37105f8ac405ab419b811da0d9819",
    detail: "6-inch downloadable imagery",
    reason: "Benton County publishes the imagery as a large downloadable archive rather than a streamable map service; the item is linked instead of being copied into MnMapping.",
  },
  {
    county: "Big Stone",
    name: "Big Stone County 2026 EagleView",
    year: 2026,
    url: "https://gis.bigstonecounty.gov/arcgis/rest/services/Imagery/2026Eagleview/MapServer",
    detail: "County aerial mosaic",
    reason: "The public service identifies EagleView/Pictometry imagery but does not publish a third-party reuse license.",
  },
  {
    county: "Blue Earth",
    name: "Blue Earth County 2025 imagery",
    year: 2025,
    url: "https://gis.blueearthcountymn.gov/server/rest/services/Basemap/Imagery2025TileService/MapServer",
    detail: "County aerial mosaic",
    reason: "The public tile service does not identify a reuse license, and the county notes that some GIS data may be restricted by third-party licensing.",
  },
  {
    county: "Brown",
    name: "Brown County GIS EagleView mosaic",
    year: 2026,
    url: "https://gis.browncountymn.gov/portal/home/item.html?id=6abb304efc674371b52c255b11b027bd",
    reason: "Brown County's EagleView agreement limits Connect Image Service use to the county's organization, and the public catalog does not grant third-party reuse rights.",
  },
  {
    county: "Brown",
    name: "Brown County GIS EagleView mosaic",
    year: 2023,
    url: "https://gis.browncountymn.gov/portal/home/item.html?id=7c66b91ebb53409a8a7f68628305a89c",
    reason: "The imagery is publicly viewable, but EagleView retains copyright and no license authorizes MnMapping to embed it.",
  },
  {
    county: "Carver",
    name: "Carver County 2026 Kucera imagery",
    year: 2026,
    url: "https://www.arcgis.com/home/item.html?id=885e446d20134be0a00d25e3b8f11544",
    detail: "County aerial mosaic",
    reason: "The official public item identifies Kucera imagery but leaves its license and access-information fields blank.",
  },
  {
    county: "Cass",
    name: "Cass County 2024 Pictometry",
    year: 2024,
    url: "https://cassweb.casscountymn.gov/arcgis/rest/services/2024_Pictometry/MapServer",
    detail: "County aerial mosaic",
    reason: "The county provides a public viewing service and downloadable tile package, but no third-party web-embedding license was found.",
  },
  {
    county: "Chippewa",
    name: "Chippewa County 2025 EagleView",
    year: 2025,
    url: "https://www.arcgis.com/home/item.html?id=7526348b75954aea9dd607d16dc7598d",
    detail: "County aerial mosaic",
    reason: "The official public web map identifies EagleView imagery but publishes no license or access information permitting third-party embedding.",
  },
  {
    county: "Chisago",
    name: "Chisago County 2025 EagleView",
    year: 2025,
    url: "https://gis.chisagocounty.us/arcgis/rest/services/2025Aerials/MapServer",
    detail: "County aerial mosaic",
    reason: "The service identifies EagleView imagery captured in April 2025 but does not publish third-party reuse terms.",
  },
  {
    county: "Clay",
    name: "Clay County 2025 EagleView",
    year: 2025,
    url: "https://map.claycountymn.gov/arcgis/rest/services/Clay_2025Imagery/ImageServer",
    detail: "Approximately 6-inch imagery",
    reason: "The public service credits EagleView copyright and does not grant MnMapping permission to embed the imagery.",
  },
  {
    county: "Clearwater",
    name: "Clearwater County 2019 Pictometry",
    year: 2019,
    url: "https://map.co.clearwater.mn.us/arcgis/rest/services/Imagery/Pictometry_2019/MapServer",
    detail: "6-inch county imagery",
    reason: "The imagery is sharper than current statewide coverage, but the Pictometry service publishes no third-party reuse license.",
  },
  {
    county: "Cook",
    name: "Cook County 2024 Pictometry priority areas",
    year: 2024,
    url: "https://www.arcgis.com/home/item.html?id=7a38242f988b4d92b2410bab75f52f11",
    detail: "3- and 6-inch partial coverage",
    reason: "The official item covers Greater Grand Marais and selected corridors rather than the whole county, and its license field is blank.",
  },
  {
    county: "Crow Wing",
    name: "Crow Wing County 2025 imagery",
    year: 2025,
    url: "https://gis.crowwing.us/cwc_external_main/rest/services/CWC_2025_WebMercator/MapServer",
    detail: "County aerial mosaic",
    reason: "The public county service does not publish copyright or reuse terms, so it remains an external viewing option pending confirmation.",
  },
  {
    county: "Dakota",
    name: "Dakota County 2025 spring Nearmap",
    year: 2025,
    url: "https://gisimg.co.dakota.mn.us/arcgis/rest/services/AerialPhotography/2025AirPhotoLeafOff6Inch_Spring/ImageServer",
    detail: "6-inch spring leaf-off imagery",
    reason: "The county item identifies Nearmap imagery but leaves its license field blank, so MnMapping links the official service rather than assuming third-party embedding rights.",
  },
  {
    county: "Dakota",
    name: "Dakota County 2025 fall Nearmap",
    year: 2025,
    url: "https://gisimg.co.dakota.mn.us/arcgis/rest/services/AerialPhotography/2025AirPhotoLeafOn6Inch_Fall/ImageServer",
    detail: "6-inch fall leaf-on imagery",
    reason: "Nearmap retains copyright, and the published license limits resale or distribution for direct commercial benefit; MnMapping therefore links the county service instead of embedding it.",
  },
  {
    county: "Dodge",
    name: "Dodge County 2026 imagery",
    year: 2026,
    url: "https://maps.co.goodhue.mn.us/server/rest/services/ImageryDC/Dodge_County_2026/MapServer",
    detail: "County aerial mosaic",
    reason: "The official public service identifies a 2026 county mosaic but publishes no provider, copyright, or reuse-license information, so MnMapping links it pending permission to embed.",
  },
  {
    county: "Douglas",
    name: "Douglas County 2026 EagleView",
    year: 2026,
    url: "https://www.arcgis.com/home/item.html?id=334246e794684515ab3c2192e16fa86b",
    detail: "County aerial mosaic",
    reason: "Douglas County's official public map uses a 2026 EagleView/Pictometry WMTS layer, but no third-party reuse license was found; the integrated 2022 two-inch MnGeo mosaic remains available in MnMapping.",
  },
  {
    county: "Faribault",
    name: "Faribault County 2025 orthophotos",
    year: 2025,
    url: "https://www.co.faribault.mn.us/gis/files/gis-data-fee-schedule",
    detail: "6-inch county; 3-inch cities",
    reason: "The county sells the SID orthomosaic by request rather than publishing a reusable streaming service, so MnMapping links the official ordering information.",
  },
  {
    county: "Fillmore",
    name: "Fillmore County 2022 EagleView",
    year: 2022,
    url: "https://www.co.fillmore.mn.us/PACKET%204.12.22.pdf",
    detail: "3-inch county imagery",
    reason: "County records identify the 2022 flight as licensed EagleView/Pictometry imagery, and no third-party web-embedding grant was found.",
  },
  {
    county: "Goodhue",
    name: "Goodhue County 2025 EagleView",
    year: 2025,
    url: "https://www.arcgis.com/home/item.html?id=d61e2110b4fa451e8f6b5728f18c5243",
    detail: "County aerial mosaic",
    reason: "The official imagery item identifies EagleView as the provider but publishes no license or access information allowing third-party embedding.",
  },
  {
    county: "Grant",
    name: "Grant County 2017 Pictometry",
    year: 2017,
    url: "https://gis.co.grant.mn.us/arcgis/rest/services/Grant/Pictometry2017/MapServer",
    detail: "Approximately 6-inch county imagery",
    reason: "The county exposes a public cached Pictometry mosaic, but the service publishes no copyright statement or third-party reuse license.",
  },
  {
    county: "Houston",
    name: "Houston County 2023 Pictometry",
    year: 2023,
    url: "https://www.hocomn.gov/departments/assessor/index.php",
    detail: "6-inch county imagery",
    reason: "Houston County directs the public to Beacon for aerial photography, while the county's 2023 Pictometry acquisition does not grant third-party embedding rights.",
  },
  {
    county: "Itasca",
    name: "Itasca County 2023 Pictometry",
    year: 2023,
    url: "https://maps-test.co.itasca.mn.us/portal/home/item.html?id=a5fa015f5196400b8bfac15ed5f2960e",
    detail: "County aerial mosaic",
    reason: "The county's official portal uses a 2023 Pictometry WMTS layer, but no third-party reuse license was found.",
  },
  {
    county: "Jackson",
    name: "Jackson County 2021 Pictometry",
    year: 2021,
    url: "https://jacksoncountymn.gov/vertical/Sites/%7B47B68709-5081-4D2D-A79C-49891B025171%7D/uploads/2021_Audit_Report-Final.pdf",
    detail: "County aerial imagery",
    reason: "The county audit confirms a 2021 Pictometry aerial flyover, but no third-party web-embedding grant was found.",
  },
  {
    county: "Kandiyohi",
    name: "Kandiyohi County 2024 Pictometry",
    year: 2024,
    url: "https://www.kcmn.us/departments/geographic_information_systems/index.php",
    detail: "Spring leaf-off high-resolution imagery",
    reason: "The county identifies its current basemap as Spring 2024 Pictometry and separately distributes imagery data by request, without granting third-party embedding rights.",
  },
  {
    county: "Le Sueur",
    name: "Le Sueur County 2025 EagleView",
    year: 2025,
    url: "https://www.lesueurcounty.gov/DocumentCenter/View/7420/2025--Le-Sueur-County-Environmental-Services-Annual-Report",
    detail: "County aerial imagery",
    reason: "The county's annual report confirms new 2025 aerials in Beacon, while the underlying EagleView imagery has no published third-party embedding license.",
  },
  {
    county: "Mahnomen",
    name: "Mahnomen County 2020 aerial photography",
    year: 2020,
    url: "https://www.arcgis.com/home/item.html?id=48fa6f5ab98c4408a1bf96f769c3071",
    detail: "County aerial mosaic",
    reason: "The official county item publishes the 2020 imagery for viewing but does not identify its provider, copyright, or an imagery-specific third-party reuse license.",
  },
  {
    county: "Mille Lacs",
    name: "Mille Lacs County 2026 flyover",
    year: 2026,
    url: "https://gis.co.mille-lacs.mn.us/arcgis/rest/services/MilleLacs_2026CountyFlyover/MapServer",
    detail: "County aerial mosaic",
    reason: "The official service confirms a 2026 county flyover but leaves its provider, copyright, and reuse-license metadata blank, so MnMapping links it pending permission to embed.",
  },
  {
    county: "Morrison",
    name: "Morrison County 2020 aerial photography",
    year: 2020,
    url: "https://www.morrisoncountymn.gov/DocumentCenter/View/3432/County-Fee-Schedule-Final-2026",
    detail: "3-inch communities; 6-inch county",
    reason: "Morrison County distributes the imagery through paid data requests and requires a signed license agreement rather than publishing a reusable streaming service.",
  },
  {
    county: "Mower",
    name: "Mower County 2023 spring imagery",
    year: 2023,
    url: "https://www.arcgis.com/home/item.html?id=09cedc89c9044d5fadfce06d6ae69320",
    detail: "6-inch spring imagery",
    reason: "The official item limits use to purposes outlined in the 2023-24 MERC orthoimagery partnership program and does not grant general third-party embedding rights.",
  },
  {
    county: "Nicollet",
    name: "Nicollet County 2020 Pictometry",
    year: 2020,
    url: "https://experience.arcgis.com/experience/3708536f919244468f0327760927620d",
    detail: "County aerial mosaic",
    reason: "The official county viewer identifies commercial Pictometry imagery, but no third-party web-embedding license was found.",
  },
  {
    county: "Nobles",
    name: "Nobles County 2024 EagleView",
    year: 2024,
    url: "https://www.co.nobles.mn.us/wp-content/uploads/2023/07/230718a-2.pdf",
    detail: "3-inch county imagery",
    reason: "The county contract describes licensed EagleView cloud imagery with a three-year refresh cycle and does not grant MnMapping third-party embedding rights.",
  },
  {
    county: "Otter Tail",
    name: "Otter Tail County 2024 aerial photography",
    year: 2024,
    url: "https://experience.arcgis.com/experience/eaec93c017004e9e8aef0e3d41b2d699",
    detail: "County aerial mosaic",
    reason: "The official county map uses a 2024 photo basemap, but its public item does not publish provider or license information allowing third-party embedding.",
  },
  {
    county: "Pennington",
    name: "Pennington County 2023 imagery",
    year: 2023,
    url: "https://gismap.co.pennington.mn.us/arcgis/rest/services/Pennington/PenningtonImagery2023/MapServer",
    detail: "County aerial mosaic",
    reason: "The official public service confirms the 2023 mosaic but publishes no provider, copyright statement, or third-party reuse license.",
  },
  {
    county: "Pipestone",
    name: "Pipestone County 2020 Pictometry",
    year: 2020,
    url: "https://www.arcgis.com/home/item.html?id=ea7d0c37011e4187a19c8d32f38b3eeb",
    detail: "County aerial mosaic",
    reason: "The official county item identifies commercial Pictometry imagery but does not publish a license granting third-party embedding rights.",
  },
  {
    county: "Polk",
    name: "Polk County 2025 EagleView",
    year: 2025,
    url: "https://www.arcgis.com/home/item.html?id=14aa1a1b3d484ebdb9135651da71e10a",
    detail: "County aerial mosaic",
    reason: "The official county viewer identifies EagleView imagery, but no third-party reuse grant was found for the commercial imagery.",
  },
  {
    county: "Pope",
    name: "Pope County 2023 Pictometry",
    year: 2023,
    url: "https://gis.popecountymn.gov/arcgis/rest/services/Imagery/2023_Pictometry/MapServer",
    detail: "County aerial mosaic",
    reason: "The official service identifies Pictometry imagery but leaves copyright and reuse-license metadata blank.",
  },
  {
    county: "Redwood",
    name: "Redwood County 2016 Pictometry",
    year: 2016,
    url: "https://redwoodcounty-mn.us/wp-content/uploads/dlm_uploads/2025/01/2025-Redwood-County-Fee-Schedule-1.pdf",
    detail: "Neighborhood- and community-resolution imagery",
    reason: "Redwood County sells the Pictometry aerial-photo sections under its fee schedule rather than publishing a reusable streaming service.",
  },
  {
    county: "Renville",
    name: "Renville County spring 2024 imagery",
    year: 2024,
    url: "https://www.renvillecountymn.gov/county-maps-gis/",
    detail: "Spring county imagery",
    reason: "The county confirms Spring 2024 imagery, but its service metadata does not identify the provider or publish a third-party reuse license.",
  },
  {
    county: "Scott",
    name: "Scott County spring 2026 orthophotos",
    year: 2026,
    url: "https://gis.co.scott.mn.us/arcgis/rest/services/Imagery/ORTHO2026/MapServer",
    detail: "Approximately 3-inch county imagery",
    reason: "The official cached service confirms Spring 2026 imagery, but its provider, copyright, and reuse-license metadata are blank.",
  },
  {
    county: "Sherburne",
    name: "Sherburne County 2024 aerial imagery",
    year: 2024,
    url: "https://www.arcgis.com/home/item.html?id=85115427cf634c8998983218ba33a4d5",
    detail: "County aerial mosaic",
    reason: "The official county catalog identifies a 2024 imagery basemap, but no imagery-specific third-party reuse license was found.",
  },
  {
    county: "Sibley",
    name: "Sibley County 2023 imagery",
    year: 2023,
    url: "https://tiles.arcgis.com/tiles/ca9pZxSKQMiPIqAL/arcgis/rest/services/23_Exp_Tile_Cache/MapServer",
    detail: "County aerial mosaic",
    reason: "The official county viewer uses this 2023 tile cache, but its public application and service do not publish a third-party reuse license.",
  },
  {
    county: "St. Louis",
    name: "St. Louis County 2023 Pictometry",
    year: 2023,
    url: "https://www.stlouiscountymn.gov/LinkClick.aspx?fileticket=6HycsaD-Ml0%3D&mid=3327&portalid=0&tabid=1076",
    detail: "High-resolution oblique and orthogonal imagery",
    reason: "The County Board authorized a commercial Pictometry acquisition for 2023, but no third-party web-embedding grant was found.",
  },
  {
    county: "Stearns",
    name: "Stearns County spring 2024 imagery",
    year: 2024,
    url: "https://gis.co.stearns.mn.us/arcgis/rest/services/Raster/Aerial2024/MapServer",
    detail: "Spring county aerial mosaic",
    reason: "The official service and downloadable zones confirm the 2024 flight, but the service publishes no provider, copyright, or third-party reuse terms.",
  },
  {
    county: "Steele",
    name: "Steele County 2025 imagery",
    year: 2025,
    url: "https://gis.steele.mn/server/rest/services/Portal_BaseData/2025_Imagery_cache/MapServer",
    detail: "County aerial mosaic",
    reason: "The official county viewer exposes the 2025 cache, but its imagery-specific provider and third-party reuse terms are not published.",
  },
  {
    county: "Swift",
    name: "Swift County 2024 EagleView",
    year: 2024,
    url: "https://swiftcounty.gov/gis",
    detail: "County aerial imagery",
    reason: "The county states that EagleView has flown its imagery every three years since 2015, establishing the 2024 cycle, but no third-party embedding license is published.",
  },
  {
    county: "Traverse",
    name: "Traverse County 2022 Pictometry",
    year: 2022,
    url: "https://www.arcgis.com/home/item.html?id=3215266c055e4a64a19264e8c88cea87",
    detail: "County aerial imagery",
    reason: "The official county catalog identifies the 2022 Pictometry imagery, but the item does not publish a third-party web-embedding grant.",
  },
  {
    county: "Washington",
    name: "Washington County 2026 imagery",
    year: 2026,
    url: "https://maps.co.washington.mn.us/arcgis/rest/services/Aerials/Aerials2026/MapServer",
    detail: "County aerial mosaic",
    reason: "The official property viewer uses this 2026 county service, but its provider, copyright, and imagery-specific reuse-license fields are blank.",
  },
  {
    county: "Wright",
    name: "Wright County 2025 aerial photography",
    year: 2025,
    url: "https://www.arcgis.com/home/item.html?id=7270ae3ba5f64e98b3dff567720f37bf",
    detail: "County aerial mosaic",
    reason: "The official historical-imagery map includes a 2025 county tile layer, while the county's aerial products require licensing and the item grants no third-party embedding rights.",
  },
  {
    county: "Yellow Medicine",
    name: "Yellow Medicine County 2025 EagleView",
    year: 2025,
    url: "https://gis.co.ym.mn.gov/arcgis/rest/services/Pictometry/2025_Eagleview/MapServer",
    detail: "County aerial mosaic",
    reason: "The official service identifies commercial EagleView/Pictometry imagery but publishes no third-party reuse license.",
  },
  {
    county: "McLeod",
    name: "McLeod County 2026 imagery",
    year: 2026,
    url: "https://tiles.arcgis.com/tiles/7sSDkfIZpd2ReAg5/arcgis/rest/services/2026_McLeod_County/MapServer",
    detail: "County aerial mosaic",
    reason: "The public county tile service is anonymously viewable but publishes no provider, copyright, or third-party reuse terms.",
  },
  {
    county: "Todd",
    name: "Todd County 2023 Pictometry",
    year: 2023,
    url: "https://www.arcgis.com/home/item.html?id=78e30997de2f4ade806aec6c0b0e47fa",
    detail: "County aerial mosaic",
    reason: "The public county-viewer web map references a commercial Pictometry WMTS endpoint and publishes no third-party embedding grant.",
  },
  {
    county: "Wadena",
    name: "Wadena County 2025 EagleView",
    year: 2025,
    url: "https://gis.co.wadena.mn.us/arcgis/rest/services/Pictometry/2025Eagleview/MapServer",
    detail: "County aerial mosaic",
    reason: "The official public service identifies commercial EagleView imagery but publishes no third-party reuse license.",
  },
  {
    county: "Watonwan",
    name: "Watonwan County 2022 EagleView",
    year: 2022,
    url: "https://www.arcgis.com/home/item.html?id=f049a777febe406a9f0dc4bf3f5254bd",
    detail: "County aerial mosaic",
    reason: "The public web map references a commercial EagleView/Pictometry WMTS endpoint and publishes no third-party embedding grant.",
  },
  {
    county: "Wilkin",
    name: "Wilkin County 2026 EagleView",
    year: 2026,
    url: "https://gisweb.co.wilkin.mn.us/arcgis/rest/services/EagleView_2026/MapServer",
    detail: "County aerial mosaic",
    reason: "The official public service identifies commercial EagleView/Pictometry imagery but publishes no third-party reuse license.",
  },
  {
    county: "Kittson",
    name: "Kittson County 2024 imagery",
    year: 2024,
    url: "https://beacon.schneidercorp.com/Application.aspx?AppID=1044&LayerID=23156&PageTypeID=1&PageID=9718",
    detail: "County viewer imagery",
    reason: "Manual review of the official Beacon viewer confirms the 2024 layer, but no reusable public imagery endpoint or third-party embedding grant was found.",
  },
  {
    county: "Kittson",
    name: "Kittson County 2019 imagery",
    year: 2019,
    url: "https://beacon.schneidercorp.com/Application.aspx?AppID=1044&LayerID=23156&PageTypeID=1&PageID=9718",
    detail: "County viewer imagery",
    reason: "Manual review of the official Beacon viewer confirms the 2019 layer, but no reusable public imagery endpoint or third-party embedding grant was found.",
  },
  {
    county: "Marshall",
    name: "Marshall County 2024 EagleView",
    year: 2024,
    url: "https://gis.co.marshall.mn.us/server/rest/services/Marshall/Marshall_2024_Eagleview_Imagery/MapServer",
    detail: "County aerial mosaic",
    reason: "The official public service identifies commercial EagleView imagery but publishes no third-party reuse license.",
  },
  {
    county: "Marshall",
    name: "Marshall County 2020 imagery",
    year: 2020,
    url: "https://gis.co.marshall.mn.us/server/rest/services/Marshall/2020_Aerial/MapServer",
    detail: "County aerial mosaic",
    reason: "The official public service publishes no provider, copyright, or third-party reuse terms.",
  },
  {
    county: "Norman",
    name: "Norman County 2025 EagleView",
    year: 2025,
    url: "https://gis.co.norman.mn.us/link/jsfe/index.aspx",
    detail: "County viewer imagery",
    reason: "Manual review of the official county viewer confirms the 2025 EagleView layer, but no reusable public imagery endpoint or third-party embedding grant was found.",
  },
  {
    county: "Norman",
    name: "Norman County 2022 EagleView",
    year: 2022,
    url: "https://gis.co.norman.mn.us/link/jsfe/index.aspx",
    detail: "County viewer imagery",
    reason: "Manual review of the official county viewer confirms the 2022 EagleView layer, but no reusable public imagery endpoint or third-party embedding grant was found.",
  },
  {
    county: "Stevens",
    name: "Stevens County 2026 Pictometry",
    year: 2026,
    url: "https://www.arcgis.com/home/item.html?id=fb922a6e864441d4b5e38473e6f86a20",
    detail: "County EagleView mosaic",
    reason: "The official public web map uses a commercial Pictometry/EagleView WMTS layer and publishes no third-party embedding grant.",
  },
  {
    county: "Stevens",
    name: "Stevens County 2023 Pictometry",
    year: 2023,
    url: "https://www.arcgis.com/home/item.html?id=024b7d0dacd44c4685f018c43b71835f",
    detail: "County EagleView mosaic",
    reason: "The official public web map uses a commercial Pictometry/EagleView WMTS layer and publishes no third-party embedding grant.",
  },
  {
    county: "Stevens",
    name: "Stevens County 2020 Pictometry",
    year: 2020,
    url: "https://gis.co.stevens.mn.us/arcgis/rest/services/2020Pictometry/MapServer",
    detail: "County aerial mosaic",
    reason: "The official public Pictometry service publishes no third-party reuse license.",
  },
] as const;

export function restrictedImageryForCounty(countyName: string): readonly RestrictedImagerySource[] {
  return restrictedImagerySources
    .filter((source) => source.county === countyName && !isIntegratedArcgisImagery(source.county, source.year, source.url))
    .toSorted((first, second) => second.year - first.year);
}
import { isIntegratedArcgisImagery } from "./layers/counties/arcgisImagery";
