import type { LayerDefinition } from "./types";

const MNGEO_IMAGERY_WMS = "/api/gis-proxy/mngeo-imagery/wmsll?";
const MNGEO_IMAGERY_SOURCE = "https://imageserver.gisdata.mn.gov/cgi-bin/wmsll?";
const MINNESOTA_IMAGERY_BOUNDS = {
  west: -97.38,
  south: 43.37,
  east: -89.33,
  north: 49.4,
} as const;

export const imageryLayers: LayerDefinition[] = [
  {
    id: "mngeo-best-available",
    name: "Best Available",
    category: "imagery",
    sourceType: "wms",
    url: "/api/gis-proxy/mngeo-imagery/mncomp?",
    sourceUrl: "https://imageserver.gisdata.mn.gov/cgi-bin/mncomp?",
    defaultVisible: true,
    defaultOpacity: 1,
    minimumLevel: 5,
    bounds: MINNESOTA_IMAGERY_BOUNDS,
    attribution: "MnGeo Composite Image Service",
    agency: "Minnesota Geospatial Information Office (MnGeo)",
    year: "Dynamic",
    resolution: "Varies by location and scale",
    description: "Automatically selects imagery using quality, resolution, recency, coverage, and season.",
    options: { layers: "mncomp", format: "image/jpeg", transparent: false, version: "1.1.1" },
  },
  ...[
    { year: 2025, resolution: "0.6 meter (approximately 2 feet)", layer: "fsa2025", color: "Natural color" },
    { year: 2025, resolution: "0.6 meter (approximately 2 feet)", layer: "fsa2025cir", color: "Color infrared" },
    { year: 2023, resolution: "0.3 meter (approximately 1 foot)", layer: "fsa2023", color: "Natural color" },
    { year: 2023, resolution: "0.3 meter (approximately 1 foot)", layer: "fsa2023cir", color: "Color infrared" },
    { year: 2021, resolution: "0.6 meter (approximately 2 feet)", layer: "fsa2021", color: "Natural color" },
    { year: 2021, resolution: "0.6 meter (approximately 2 feet)", layer: "fsa2021cir", color: "Color infrared" },
    { year: 2019, resolution: "0.6 meter (approximately 2 feet)", layer: "fsa2019", color: "Natural color" },
    { year: 2019, resolution: "0.6 meter (approximately 2 feet)", layer: "fsa2019cir", color: "Color infrared" },
  ].map(({ year, resolution, layer, color }): LayerDefinition => ({
    id: `mngeo-naip-${year}${color === "Color infrared" ? "-cir" : ""}`,
    name: `${year} NAIP${color === "Color infrared" ? " CIR" : ""}`,
    category: "imagery",
    sourceType: "wms",
    url: MNGEO_IMAGERY_WMS,
    sourceUrl: MNGEO_IMAGERY_SOURCE,
    defaultVisible: false,
    defaultOpacity: 1,
    minimumLevel: 5,
    bounds: MINNESOTA_IMAGERY_BOUNDS,
    attribution: "USDA Farm Service Agency via MnGeo",
    agency: "USDA Farm Service Agency; hosted by MnGeo",
    year,
    resolution,
    description: `Statewide summer ${color.toLowerCase()} National Agriculture Imagery Program imagery.`,
    imageryGroup: color === "Color infrared" ? "cir" : "naip",
    options: { layers: layer, format: "image/jpeg", transparent: false, version: "1.1.1" },
  })),
  {
    id: "mngeo-usgs-doq-1991",
    name: "1991 USGS DOQ",
    category: "imagery",
    sourceType: "wms",
    url: MNGEO_IMAGERY_WMS,
    sourceUrl: MNGEO_IMAGERY_SOURCE,
    defaultVisible: false,
    defaultOpacity: 1,
    minimumLevel: 5,
    bounds: { west: -97.54, south: 43.42, east: -89.33, north: 49.4 },
    attribution: "USGS Digital Orthophoto Quadrangles via MnGeo",
    agency: "United States Geological Survey; hosted by MnGeo",
    year: 1991,
    resolution: "Resolution varies by source tile",
    description: "Historical black-and-white USGS orthophotography for visual comparison.",
    options: { layers: "doq", format: "image/jpeg", transparent: false, version: "1.1.1" },
  },
];
