import type { LayerDefinition } from "./types";

const serviceRoot = "/api/gis-proxy/mngeo-features/us_mn_state_dnr";
const sourceRoot = "https://enterprise.gisdata.mn.gov/aghost/rest/services/us_mn_state_dnr";

export const publicLandLayers: LayerDefinition[] = [
  {
    id: "mndnr-public-wmas",
    name: "Publicly Accessible WMAs",
    category: "public-land",
    sourceType: "arcgis-featureserver",
    url: `${serviceRoot}/bdry_dnr_wildlife_mgmt_areas_pub/FeatureServer`,
    sourceUrl: `${sourceRoot}/bdry_dnr_wildlife_mgmt_areas_pub/FeatureServer/0`,
    defaultVisible: false,
    defaultOpacity: 0.82,
    attribution: "Minnesota DNR Wildlife",
    agency: "Minnesota Department of Natural Resources",
    description: "State wildlife management area polygons published specifically as publicly accessible. Site restrictions and closures still control access.",
    accessMeaning: "public-access",
    nameField: "unit_name",
    popupFields: [
      { field: "unit_name", label: "WMA" },
      { field: "subunit_name", label: "Subunit" },
      { field: "managing_admin_office", label: "Managing office" },
      { field: "gis_area_acres", label: "GIS acres" },
      { field: "general_access_notes", label: "Access notes" },
      { field: "special_restrictions", label: "Restrictions" },
    ],
    options: { layerId: 0, outFields: "unit_name,subunit_name,managing_admin_office,gis_area_acres,general_access_notes,special_restrictions", fillColor: "#7458a6", strokeColor: "#c9b4f2", fillAlpha: 0.28, strokeWidth: 2 },
  },
  {
    id: "mndnr-sna-units",
    name: "Scientific & Natural Areas",
    category: "public-land",
    sourceType: "arcgis-featureserver",
    url: `${serviceRoot}/bdry_scientific_and_nat_areas/FeatureServer`,
    sourceUrl: `${sourceRoot}/bdry_scientific_and_nat_areas/FeatureServer/4`,
    defaultVisible: false,
    defaultOpacity: 0.82,
    attribution: "Minnesota DNR Scientific and Natural Areas",
    agency: "Minnesota Department of Natural Resources",
    description: "SNA unit boundaries. Ownership and allowable activities vary; consult the DNR unit information before visiting.",
    accessMeaning: "managed-land",
    nameField: "unit_name",
    popupFields: [
      { field: "unit_name", label: "SNA" },
      { field: "unit_type", label: "Unit type" },
      { field: "gis_acres", label: "GIS acres" },
      { field: "own_desc", label: "Ownership" },
      { field: "point_of_contact", label: "Contact" },
    ],
    options: { layerId: 4, outFields: "unit_name,unit_type,gis_acres,own_desc,point_of_contact", fillColor: "#d8912f", strokeColor: "#ffd18b", fillAlpha: 0.24, strokeWidth: 2 },
  },
  {
    id: "mndnr-parks-units",
    name: "State Parks & Recreation Units",
    category: "public-land",
    sourceType: "arcgis-featureserver",
    url: `${serviceRoot}/bdry_dnr_lrs_prk/FeatureServer`,
    sourceUrl: `${sourceRoot}/bdry_dnr_lrs_prk/FeatureServer/2`,
    defaultVisible: false,
    defaultOpacity: 0.82,
    attribution: "Minnesota DNR Parks and Trails",
    agency: "Minnesota Department of Natural Resources",
    description: "Park, recreation-area, and wayside management units. These are unit boundaries and should not be interpreted as parcel-level ownership.",
    accessMeaning: "administrative-boundary",
    nameField: "unit_name",
    popupFields: [
      { field: "unit_name", label: "Management unit" },
      { field: "unit_type", label: "Unit type" },
      { field: "legislative_name", label: "Legislative name" },
      { field: "gis_acres", label: "GIS acres" },
    ],
    options: { layerId: 2, outFields: "unit_name,unit_type,legislative_name,gis_acres", fillColor: "#2789a3", strokeColor: "#94dfef", fillAlpha: 0.24, strokeWidth: 2 },
  },
  {
    id: "mndnr-ama-acquisitions",
    name: "Aquatic Management Acquisitions",
    category: "public-land",
    sourceType: "arcgis-featureserver",
    url: `${serviceRoot}/plan_mndnr_fisheries_acquisition/FeatureServer`,
    sourceUrl: `${sourceRoot}/plan_mndnr_fisheries_acquisition/FeatureServer/0`,
    defaultVisible: false,
    defaultOpacity: 0.82,
    attribution: "Minnesota DNR Fisheries",
    agency: "Minnesota Department of Natural Resources",
    description: "DNR fisheries acquisition interests associated with aquatic management. Interest type and public access vary by parcel.",
    accessMeaning: "access-varies",
    nameField: "unit_name",
    popupFields: [
      { field: "unit_name", label: "Unit" },
      { field: "int_type", label: "Interest type" },
      { field: "acq_type", label: "Acquisition type" },
      { field: "admin_unit", label: "Admin unit" },
      { field: "gis_acres", label: "GIS acres" },
      { field: "web_notes", label: "Notes" },
    ],
    options: { layerId: 0, outFields: "unit_name,int_type,acq_type,admin_unit,gis_acres,web_notes", fillColor: "#2778bd", strokeColor: "#9ed0ff", fillAlpha: 0.25, strokeWidth: 2 },
  },
  {
    id: "mndnr-state-forest-management",
    name: "State Forest Management Units",
    category: "public-land",
    sourceType: "arcgis-featureserver",
    url: `${serviceRoot}/bdry_state_forest/FeatureServer`,
    sourceUrl: `${sourceRoot}/bdry_state_forest/FeatureServer/3`,
    defaultVisible: false,
    defaultOpacity: 0.82,
    attribution: "Minnesota DNR Forestry",
    agency: "Minnesota Department of Natural Resources",
    description: "State forest management units. A management boundary does not establish public ownership of every enclosed parcel.",
    accessMeaning: "administrative-boundary",
    nameField: "unit_name",
    popupFields: [
      { field: "unit_name", label: "Forest unit" },
      { field: "administrator", label: "Administrator" },
      { field: "gis_acres", label: "GIS acres" },
      { field: "access_wo_trespass", label: "Access without trespass" },
      { field: "point_of_contact", label: "Contact" },
    ],
    options: { layerId: 3, outFields: "unit_name,administrator,gis_acres,access_wo_trespass,point_of_contact", fillColor: "#2d7d4d", strokeColor: "#9fe0ae", fillAlpha: 0.2, strokeWidth: 2 },
  },
];
