import type { LayerDefinition } from "./types";

export const statewideLayers: LayerDefinition[] = [
  {
    id: "natural-earth",
    name: "Natural Earth",
    category: "basemap",
    sourceType: "tms",
    url: "/cesium/Assets/Textures/NaturalEarthII",
    defaultVisible: true,
    defaultOpacity: 1,
    attribution: "Natural Earth II imagery bundled with CesiumJS",
    description: "Offline, low-resolution starter basemap. Statewide imagery is added in Step 03.",
  },
  {
    id: "esri-roads-reference",
    name: "Roads & Highways",
    category: "reference",
    sourceType: "arcgis-mapserver",
    url: "/api/gis-proxy/esri-reference/Reference/World_Transportation/MapServer",
    sourceUrl: "https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Transportation/MapServer",
    defaultVisible: false,
    defaultOpacity: 1,
    attribution: "Esri, HERE, Garmin, and OpenStreetMap contributors",
    agency: "Esri World Transportation reference map",
    resolution: "Multiresolution label overlay",
    description: "Roads, highways, railroads, and airports, purpose-built by Esri as a label overlay for dark or imagery basemaps. Useful for orientation while comparing aerial imagery. Publicly served without an API key from the same Esri host this app already uses for the location-picker basemaps.",
    options: { enablePickFeatures: false },
  },
  {
    id: "esri-places-reference",
    name: "Place Labels & Boundaries",
    category: "reference",
    sourceType: "arcgis-mapserver",
    url: "/api/gis-proxy/esri-reference/Reference/World_Boundaries_and_Places/MapServer",
    sourceUrl: "https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer",
    defaultVisible: false,
    defaultOpacity: 1,
    attribution: "Esri, HERE, Garmin, and OpenStreetMap contributors",
    agency: "Esri World Boundaries and Places reference map",
    resolution: "Multiresolution label overlay",
    description: "City, town, and other place names with country, state, and county boundary lines, purpose-built by Esri as a label overlay for dark or imagery basemaps.",
    options: { enablePickFeatures: false },
  },
];
